### Register user
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "username": "andrew",
  "password": "password",
  "email": "andrew@email.com"
}

### Authenticate user
POST http://localhost:8080/api/v1/authenticate?username=andrew&password=password

> {% client.global.set("auth_token", response.headers.valueOf("Authorization")); %}

### Private API without token
GET http://localhost:8080/api/v1/users/secure

### Private API
GET http://localhost:8080/api/v1/users/secure
Authorization: {{auth_token}}

### Add location to user
POST http://localhost:8080/api/v1/locations
Authorization: {{auth_token}}
Content-Type: application/json

{
  "city": "Berlin",
  "street": "Warschauerstrasse",
  "number": "12"
}

> {% client.global.set("location_uuid", response.body.payload.uuid); %}

### Get users added locations
GET http://localhost:8080/api/v1/locations
Authorization: {{auth_token}}

### Route creation
POST http://localhost:8080/api/v1/routes
Authorization: {{auth_token}}
Content-Type: application/json

{
  "startDate": "23.12.2020 08:30",
  "maxEndDate": "27.12.2020 18:00",
  "traffic": "best_guess",
  "name": "CW52"
}

> {% client.global.set("route_uuid", response.body.payload.uuid); %}

### Get single route
GET http://localhost:8080/api/v1/routes/{{route_uuid}}
Authorization: {{auth_token}}

### Add route location with existing in db location
POST http://localhost:8080/api/v1/routes/{{route_uuid}}/locations
Authorization: {{auth_token}}
Content-Type: application/json

{
  "priority": "optional",
  "onsideDuration": "01:30",
  "existingLocationUuid": "{{location_uuid}}",
  "availability": [
    {
      "date": "20.12.2020",
      "excluded": true
    },
    {
      "date": "19.12.2020",
      "from": "12:00",
      "to": "14:00"
    }
  ]
}

### Add route location with non existing in db location
POST http://localhost:8080/api/v1/routes/{{route_uuid}}/locations
Authorization: {{auth_token}}
Content-Type: application/json

{
  "priority": "optional",
  "onsideDuration": "01:30",
  "location": {
    "city": "Warszawa",
    "street": "Marszałkowska",
    "number": "5"
  },
  "availability": [
    {
      "date": "20.12.2020",
      "excluded": true
    },
    {
      "date": "19.12.2020",
      "from": "12:00",
      "to": "14:00"
    }
  ]
}

### Add route start location with non existing in db location
POST http://localhost:8080/api/v1/routes/{{route_uuid}}/locations/startLocation
Authorization: {{auth_token}}
Content-Type: application/json

{
  "city": "Wrocław",
  "street": "Słowiańska",
  "number": "10"
}

### Add location to user (for route start location)
POST http://localhost:8080/api/v1/locations
Authorization: {{auth_token}}
Content-Type: application/json

{
  "city": "Bielany Wrocławskie",
  "street": "Logistyczna",
  "number": "12"
}

> {% client.global.set("end_location_uuid", response.body.payload.uuid); %}

### Add route end location with existing in db location
PUT http://localhost:8080/api/v1/routes/{{route_uuid}}/locations/endLocation?locationUuid={{end_location_uuid}}
Authorization: {{auth_token}}
Content-Type: application/json

###