### Register user
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "username": "andrew",
  "password": "password",
  "email": "andrew@email.com"
}

### Authenticate user
POST http://localhost:8080/api/v1/authenticate?username=andrew&password=password

> {% client.global.set("auth_token", response.headers.valueOf("Authorization")); %}

### Public API
GET http://localhost:8080/api/v1/users/secure

### Private API
GET http://localhost:8080/api/v1/users/secure
Authorization: {{auth_token}}

### Route creation
POST http://localhost:8080/api/v1/routes
Authorization: {{auth_token}}
Content-Type: application/json

{
  "startDate": "18.12.2019 08:30",
  "maxEndDate": "24.12.2019 18:00",
  "traffic": "best_guess",
  "name": "CW52"
}

> {% client.global.set("route_uuid", response.body.payload.uuid); %}

### Get single route
GET http://localhost:8080/api/v1/routes/{{route_uuid}}
Authorization: {{auth_token}}

### Add route location
POST http://localhost:8080/api/v1/routes/{{route_uuid}}/locations
Authorization: {{auth_token}}
Content-Type: application/json

{
  "priority": "optional",
  "onsideDuration": "01:30",
  "existingLocationId": 1,
  "availability": [
    {
      "date": "20.12.2019",
      "excluded": true
    },
    {
      "date": "19.12.2019",
      "from": "12:00",
      "to": "14:00"
    }
  ]
}

###